services:
  postgres:
    image: timescale/timescaledb:2.13.0-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend_network

volumes:
  pgdata:
  mongodata:

networks:
  backend_network:
    driver: bridge
